function [default,sep,line_sep,header,setting_elements] = config_file_definitions()

% ---------------------------------------------------
% Header definition
% ---------------------------------------------------

default.First_Run_Select_Time_Period.Name = 'FIRST_RUN_SELECT_TIME_PERIOD';
default.First_Run_Select_Time_Period.Val = 1;

default.First_Run_Merge_Results.Name = 'FIRST_RUN_MERGE_RESULTS';
default.First_Run_Merge_Results.Val = 1;

default.Save_Time_Domain.Name = 'SAVE_TIME_DOMAIN';
default.Save_Time_Domain.Val = 1;

% ---------------------------------------------------
sep = ';';
line_sep = '\r\n';
header = '[NVIEW CONFIGURATION FILE, AUTOGENERATED BY NVIEW]';

setting_elements = fields(default);

end